//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelStream {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FileResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FileResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExcelStream.FileResources", typeof(FileResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;Relationships xmlns=&quot;http://schemas.openxmlformats.org/package/2006/relationships&quot;&gt;
        ///	&lt;Relationship Id=&quot;rId1&quot; Type=&quot;http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument&quot; Target=&quot;xl/workbook.xml&quot;/&gt;
        ///&lt;/Relationships&gt;.
        /// </summary>
        internal static string rels {
            get {
                return ResourceManager.GetString("rels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;styleSheet xmlns=&quot;http://schemas.openxmlformats.org/spreadsheetml/2006/main&quot; xmlns:mc=&quot;http://schemas.openxmlformats.org/markup-compatibility/2006&quot; mc:Ignorable=&quot;x14ac&quot; xmlns:x14ac=&quot;http://schemas.microsoft.com/office/spreadsheetml/2009/9/ac&quot;&gt;
        ///	&lt;fonts count=&quot;18&quot; x14ac:knownFonts=&quot;1&quot;&gt;
        ///		&lt;font&gt;
        ///			&lt;sz val=&quot;11&quot;/&gt;
        ///			&lt;color theme=&quot;1&quot;/&gt;
        ///			&lt;name val=&quot;Calibri&quot;/&gt;
        ///			&lt;family val=&quot;2&quot;/&gt;
        ///			&lt;scheme val=&quot;minor&quot;/&gt;
        ///		&lt;/font&gt;
        ///		&lt;font&gt;
        ///			&lt;sz val=&quot;11&quot;/&gt;
        ///	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string styles {
            get {
                return ResourceManager.GetString("styles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;a:theme xmlns:a=&quot;http://schemas.openxmlformats.org/drawingml/2006/main&quot; name=&quot;Office Theme&quot;&gt;
        ///	&lt;a:themeElements&gt;
        ///		&lt;a:clrScheme name=&quot;Office&quot;&gt;
        ///			&lt;a:dk1&gt;
        ///				&lt;a:sysClr val=&quot;windowText&quot; lastClr=&quot;000000&quot;/&gt;
        ///			&lt;/a:dk1&gt;
        ///			&lt;a:lt1&gt;
        ///				&lt;a:sysClr val=&quot;window&quot; lastClr=&quot;FFFFFF&quot;/&gt;
        ///			&lt;/a:lt1&gt;
        ///			&lt;a:dk2&gt;
        ///				&lt;a:srgbClr val=&quot;44546A&quot;/&gt;
        ///			&lt;/a:dk2&gt;
        ///			&lt;a:lt2&gt;
        ///				&lt;a:srgbClr val=&quot;E7E6E6&quot;/&gt;
        ///			&lt;/a:lt2&gt;
        ///			&lt;a:accent1&gt;
        ///				&lt;a:srgbClr val=&quot;5B9BD5&quot;/&gt;
        ///		 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string theme1 {
            get {
                return ResourceManager.GetString("theme1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;workbook xmlns=&quot;http://schemas.openxmlformats.org/spreadsheetml/2006/main&quot; xmlns:r=&quot;http://schemas.openxmlformats.org/officeDocument/2006/relationships&quot; xmlns:mc=&quot;http://schemas.openxmlformats.org/markup-compatibility/2006&quot; mc:Ignorable=&quot;x15&quot; xmlns:x15=&quot;http://schemas.microsoft.com/office/spreadsheetml/2010/11/main&quot;&gt;
        ///	&lt;fileVersion appName=&quot;xl&quot; lastEdited=&quot;6&quot; lowestEdited=&quot;6&quot; rupBuild=&quot;14420&quot;/&gt;
        ///	&lt;sheets&gt;
        ///		&lt;sheet name=&quot;Sheet1&quot; sheetId=&quot;1&quot; r:id=&quot;rId [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string workbook {
            get {
                return ResourceManager.GetString("workbook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;Relationships xmlns=&quot;http://schemas.openxmlformats.org/package/2006/relationships&quot;&gt;
        ///	&lt;Relationship Id=&quot;rId3&quot; Type=&quot;http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles&quot; Target=&quot;styles.xml&quot;/&gt;
        ///	&lt;Relationship Id=&quot;rId2&quot; Type=&quot;http://schemas.openxmlformats.org/officeDocument/2006/relationships/theme&quot; Target=&quot;theme/theme1.xml&quot;/&gt;
        ///	&lt;Relationship Id=&quot;rId1&quot; Type=&quot;http://schemas.openxmlformats.org/officeDocument/2006/relationships/works [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string workbook_xml_rels {
            get {
                return ResourceManager.GetString("workbook_xml_rels", resourceCulture);
            }
        }
    }
}
